# TCL File Generated by Component Editor on: 
# Mon May 14 15:31:17 PDT 2007
# DO NOT MODIFY

set_source_file "altera_avalon_remote_update_cycloneiii.v"
set_module "altera_avalon_remote_update_cycloneiii"
set_module_description ""
set_module_property "className" "altera_avalon_remote_update_cycloneiii"
set_module_property instantiateInSystemModule true
set_module_property author  "Altera Corporation"
set_module_property version "8.0"
set_module_property group "Peripherals/FPGA Peripherals"
set_module_property editable false
set_module_property simulationFiles [ list "altera_avalon_remote_update_cycloneiii.v" ]
set_module_property synthesisFiles [ list "altera_avalon_remote_update_cycloneiii.v" ]
set_module_property displayName "Remote Update Controller (Cyclone III)"
set_module_property datasheetURL "http://www.altera.com/literature/quartus2/lit-qts-peripherals.jsp"
set_module_property simulationModelInVHDL "true"
set_module_property simulationModelInVerilog "true"

# Module parameters

set_module_property previewElaborationCallback "elaborate"
proc elaborate {} {

	# Clock Interface global_signals_clock
	add_clock_interface "global_signals_clock" 
	set_interface_property "global_signals_clock" "externallyDriven" "false"
	set_interface_property "global_signals_clock" "clockRateKnown" "false"
	set_interface_property "global_signals_clock" "clockRate" "0"
	# Ports in interface global_signals_clock
	add_port_to_interface "global_signals_clock" "clk" "clk"
	add_port_to_interface "global_signals_clock" "reset" "reset"
	
	# Interface s1
	add_interface "s1" "avalon" "slave" "global_signals_clock"
	set_interface_property "s1" "isNonVolatileStorage" "false"
	set_interface_property "s1" "burstOnBurstBoundariesOnly" "false"
	set_interface_property "s1" "transparentBridge" "false"
	set_interface_property "s1" "readLatency" "2"
	set_interface_property "s1" "readWaitStates" "0"
	set_interface_property "s1" "isFlash" "false"
	set_interface_property "s1" "holdTime" "0"
	set_interface_property "s1" "printableDevice" "false"
	set_interface_property "s1" "registerIncomingSignals" "false"
	set_interface_property "s1" "readWaitTime" "0"
	set_interface_property "s1" "setupTime" "0"
	set_interface_property "s1" "addressGroup" "0"
	set_interface_property "s1" "interleaveBursts" "false"
	set_interface_property "s1" "addressAlignment" "NATIVE"
	set_interface_property "s1" "isBigEndian" "false"
	set_interface_property "s1" "writeLatency" "0"
	set_interface_property "s1" "writeWaitTime" "0"
	set_interface_property "s1" "timingUnits" "Cycles"
	set_interface_property "s1" "minimumUninterruptedRunLength" "1"
	set_interface_property "s1" "registerOutgoingSignals" "false"
	set_interface_property "s1" "addressSpan" "64"
	set_interface_property "s1" "isMemoryDevice" "false"
	set_interface_property "s1" "linewrapBursts" "false"
	set_interface_property "s1" "alwaysBurstMaxBurst" "false"
	set_interface_property "s1" "writeWaitStates" "0"
	set_interface_property "s1" "maximumPendingReadTransactions" "0"
	set_interface_property "s1" "wellBehavedWaitrequest" "false"
	# Ports in interface s1
	add_port_to_interface "s1" "writedata" "writedata"
	set_port_direction_and_width "writedata" "input" 32
	add_port_to_interface "s1" "readdata" "readdata"
	set_port_direction_and_width "readdata" "output" 32
	add_port_to_interface "s1" "address" "address"
	set_port_direction_and_width "address" "input" 6
	add_port_to_interface "s1" "chipselect" "chipselect"
	set_port_direction_and_width "chipselect" "input" 1
	add_port_to_interface "s1" "write" "write"
	set_port_direction_and_width "write" "input" 1
	add_port_to_interface "s1" "read" "read"
	set_port_direction_and_width "read" "input" 1
	add_port_to_interface "s1" "waitrequest" "waitrequest"
	set_port_direction_and_width "waitrequest" "output" 1
}
