# Caution: this file may be regenerated by SOPC Builder.  User edits will be lost.
project_open -current_revision "/home/netlab/ngunton/Av_Sys_rtos/standard/cycloneIII_3c25_niosII_standard.qpf"
project_close