# TCL File Generated by Component Editor 11.0sp1
# Tue Feb 11 10:41:58 GMT 2014
# DO NOT MODIFY


# +-----------------------------------
# | 
# | my_pwm "my_pwm" v1.0
# | null 2014.02.11.10:41:58
# | 
# | 
# | /home/netlab/s2hughes/Altera_Systems_Labs/EDM_Standard/my_pwm.vhd
# | 
# |    ./my_pwm.vhd syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 11.0
# | 
package require -exact sopc 11.0
# | 
# +-----------------------------------

# +-----------------------------------
# | module my_pwm
# | 
set_module_property NAME my_pwm
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property DISPLAY_NAME my_pwm
set_module_property TOP_LEVEL_HDL_FILE my_pwm.vhd
set_module_property TOP_LEVEL_HDL_MODULE my_pwm
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL TRUE
set_module_property STATIC_TOP_LEVEL_MODULE_NAME my_pwm
set_module_property FIX_110_VIP_PATH false
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file my_pwm.vhd {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock
# | 
add_interface clock clock end
set_interface_property clock clockRate 0

set_interface_property clock ENABLED true

add_interface_port clock clk clk Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_slave_0
# | 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressAlignment DYNAMIC
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 isMemoryDevice false
set_interface_property avalon_slave_0 isNonVolatileStorage false
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 printableDevice false
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0

set_interface_property avalon_slave_0 ENABLED true

add_interface_port avalon_slave_0 data_in writedata Input 32
add_interface_port avalon_slave_0 address address Input 2
add_interface_port avalon_slave_0 cs_n chipselect_n Input 1
add_interface_port avalon_slave_0 wr_n write_n Input 1
add_interface_port avalon_slave_0 data_out readdata Output 32
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point pwm_out
# | 
add_interface pwm_out conduit end

set_interface_property pwm_out ENABLED true

add_interface_port pwm_out pwm_out export Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point reset_sink
# | 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock
set_interface_property reset_sink synchronousEdges DEASSERT

set_interface_property reset_sink ENABLED true

add_interface_port reset_sink resetn reset_n Input 1
# | 
# +-----------------------------------
