package require ::quartus::project

set_location_assignment PIN_V9 -to osc_clk 
set_location_assignment PIN_N2 -to reset_n 
set_location_assignment PIN_D18 -to flash_wr_n 
set_location_assignment PIN_E2 -to flash_cs_n 
set_location_assignment PIN_D17 -to flash_oe_n 
set_location_assignment PIN_C3 -to flash_reset_n 
set_location_assignment PIN_A6 -to flash_ssram_a[20] 
set_location_assignment PIN_B18 -to flash_ssram_a[21] 
set_location_assignment PIN_C17 -to flash_ssram_a[22] 
set_location_assignment PIN_C18 -to flash_ssram_a[23] 
set_location_assignment PIN_G14 -to flash_ssram_a[24] 
set_location_assignment PIN_B17 -to flash_ssram_a[25] 
set_location_assignment PIN_E12 -to flash_ssram_a[1] 
set_location_assignment PIN_A16 -to flash_ssram_a[2] 
set_location_assignment PIN_B16 -to flash_ssram_a[3] 
set_location_assignment PIN_A15 -to flash_ssram_a[4] 
set_location_assignment PIN_B15 -to flash_ssram_a[5] 
set_location_assignment PIN_A14 -to flash_ssram_a[6] 
set_location_assignment PIN_B14 -to flash_ssram_a[7] 
set_location_assignment PIN_A13 -to flash_ssram_a[8] 
set_location_assignment PIN_B13 -to flash_ssram_a[9] 
set_location_assignment PIN_A12 -to flash_ssram_a[10] 
set_location_assignment PIN_B12 -to flash_ssram_a[11] 
set_location_assignment PIN_A11 -to flash_ssram_a[12] 
set_location_assignment PIN_B11 -to flash_ssram_a[13] 
set_location_assignment PIN_C10 -to flash_ssram_a[14] 
set_location_assignment PIN_D10 -to flash_ssram_a[15] 
set_location_assignment PIN_E10 -to flash_ssram_a[16] 
set_location_assignment PIN_C9 -to flash_ssram_a[17] 
set_location_assignment PIN_D9 -to flash_ssram_a[18] 
set_location_assignment PIN_A7 -to flash_ssram_a[19] 
set_location_assignment PIN_H3 -to flash_ssram_d[0] 
set_location_assignment PIN_D1 -to flash_ssram_d[1] 
set_location_assignment PIN_D2 -to flash_ssram_d[19] 
set_location_assignment PIN_A8 -to flash_ssram_d[2] 
set_location_assignment PIN_B8 -to flash_ssram_d[3] 
set_location_assignment PIN_B7 -to flash_ssram_d[4] 
set_location_assignment PIN_C5 -to flash_ssram_d[5] 
set_location_assignment PIN_E8 -to flash_ssram_d[6] 
set_location_assignment PIN_A4 -to flash_ssram_d[7] 
set_location_assignment PIN_B4 -to flash_ssram_d[8] 
set_location_assignment PIN_E7 -to flash_ssram_d[9] 
set_location_assignment PIN_A3 -to flash_ssram_d[10] 
set_location_assignment PIN_B3 -to flash_ssram_d[11] 
set_location_assignment PIN_D5 -to flash_ssram_d[12] 
set_location_assignment PIN_B5 -to flash_ssram_d[13] 
set_location_assignment PIN_A5 -to flash_ssram_d[14] 
set_location_assignment PIN_B6 -to flash_ssram_d[15] 
set_location_assignment PIN_C16 -to flash_ssram_d[16] 
set_location_assignment PIN_D12 -to flash_ssram_d[17] 
set_location_assignment PIN_E11 -to flash_ssram_d[18] 
set_location_assignment PIN_E13 -to flash_ssram_d[20] 
set_location_assignment PIN_E14 -to flash_ssram_d[21] 
set_location_assignment PIN_A17 -to flash_ssram_d[22] 
set_location_assignment PIN_D16 -to flash_ssram_d[23] 
set_location_assignment PIN_C12 -to flash_ssram_d[24] 
set_location_assignment PIN_A18 -to flash_ssram_d[25] 
set_location_assignment PIN_F8 -to flash_ssram_d[26] 
set_location_assignment PIN_D7 -to flash_ssram_d[27] 
set_location_assignment PIN_F6 -to flash_ssram_d[28] 
set_location_assignment PIN_E6 -to flash_ssram_d[29] 
set_location_assignment PIN_G6 -to flash_ssram_d[30] 
set_location_assignment PIN_C7 -to flash_ssram_d[31] 
set_location_assignment PIN_E9 -to ssram_oe_n 
set_location_assignment PIN_F9 -to ssram_ce_n 
set_location_assignment PIN_F10 -to ssram_bw_n[0] 
set_location_assignment PIN_F11 -to ssram_bw_n[1] 
set_location_assignment PIN_F12 -to ssram_bw_n[2] 
set_location_assignment PIN_F13 -to ssram_bw_n[3] 
set_location_assignment PIN_F7 -to ssram_adsc_n 
set_location_assignment PIN_G13 -to ssram_bwe_n

set_location_assignment PIN_U2 -to mem_clk 
set_location_assignment PIN_V2 -to mem_clk_n 
set_location_assignment PIN_V1 -to mem_cs_n 
set_location_assignment PIN_R13 -to mem_cke 
set_location_assignment PIN_U1 -to mem_addr[0] 
set_location_assignment PIN_U5 -to mem_addr[1] 
set_location_assignment PIN_U7 -to mem_addr[2] 
set_location_assignment PIN_U8 -to mem_addr[3] 
set_location_assignment PIN_P8 -to mem_addr[4] 
set_location_assignment PIN_P7 -to mem_addr[5] 
set_location_assignment PIN_P6 -to mem_addr[6] 
set_location_assignment PIN_T14 -to mem_addr[7] 
set_location_assignment PIN_T13 -to mem_addr[8] 
set_location_assignment PIN_V13 -to mem_addr[9] 
set_location_assignment PIN_U17 -to mem_addr[10] 
set_location_assignment PIN_V17 -to mem_addr[11] 
set_location_assignment PIN_U16 -to mem_addr[12] 
set_location_assignment PIN_V11 -to mem_ba[0] 
set_location_assignment PIN_V12 -to mem_ba[1] 
set_location_assignment PIN_V16 -to mem_ras_n 
set_location_assignment PIN_T4 -to mem_cas_n 
set_location_assignment PIN_U15 -to mem_we_n 
set_location_assignment PIN_U4 -to mem_dq[0] 
set_location_assignment PIN_V4 -to mem_dq[1] 
set_location_assignment PIN_R8 -to mem_dq[2] 
set_location_assignment PIN_V5 -to mem_dq[3] 
set_location_assignment PIN_P9 -to mem_dq[4] 
set_location_assignment PIN_U6 -to mem_dq[5] 
set_location_assignment PIN_V6 -to mem_dq[6] 
set_location_assignment PIN_V7 -to mem_dq[7] 
set_location_assignment PIN_U13 -to mem_dq[8] 
set_location_assignment PIN_U12 -to mem_dq[9] 
set_location_assignment PIN_U11 -to mem_dq[10] 
set_location_assignment PIN_V15 -to mem_dq[11] 
set_location_assignment PIN_U14 -to mem_dq[12] 
set_location_assignment PIN_R11 -to mem_dq[13] 
set_location_assignment PIN_P10 -to mem_dq[14] 
set_location_assignment PIN_V14 -to mem_dq[15] 
set_location_assignment PIN_U3 -to mem_dqs[0] 
set_location_assignment PIN_T8 -to mem_dqs[1] 
set_location_assignment PIN_V3 -to mem_dm[0] 
set_location_assignment PIN_V8 -to mem_dm[1]

set_location_assignment PIN_P13 -to led[0] 
set_location_assignment PIN_T1 -to led[1] 
set_location_assignment PIN_N12 -to led[2] 
set_location_assignment PIN_N9 -to led[3] 
set_location_assignment PIN_A2 -to ssram_clk 
set_instance_assignment -name VIRTUAL_PIN ON -to flash_ssram_a[0] 
set_instance_assignment -name OUTPUT_ENABLE_GROUP 1191024410 -to led[0] 
set_instance_assignment -name OUTPUT_ENABLE_GROUP 1191024410 -to led[1] 
set_instance_assignment -name OUTPUT_ENABLE_GROUP 1191024410 -to led[2] 
set_instance_assignment -name OUTPUT_ENABLE_GROUP 1191024410 -to led[3] 
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to ssram_adsc_n 
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to ssram_bw_n 
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to ssram_ce_n 
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to ssram_oe_n 
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to ssram_bwe_n 
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to ssram_clk

set_location_assignment PLL_4 -to "*|ddr_sdram:the_ddr_sdram|*|pll1" 
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to mem_clk[0] 
set_instance_assignment -name IO_STANDARD "SSTL-2 CLASS I" -to mem_clk[0] 
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to mem_clk_n[0] 
set_instance_assignment -name IO_STANDARD "SSTL-2 CLASS I" -to mem_clk_n[0] 
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to mem_cs_n[0] 
set_instance_assignment -name IO_STANDARD "SSTL-2 CLASS I" -to mem_cs_n[0] 
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to mem_cke[0] 
set_instance_assignment -name IO_STANDARD "SSTL-2 CLASS I" -to mem_cke[0] 
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to mem_addr[0] 
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to mem_addr[1] 
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to mem_addr[2] 
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to mem_addr[3] 
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to mem_addr[4] 
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to mem_addr[5] 
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to mem_addr[6] 
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to mem_addr[7] 
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to mem_addr[8] 
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to mem_addr[9] 
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to mem_addr[10] 
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to mem_addr[11] 
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to mem_addr[12] 
set_instance_assignment -name IO_STANDARD "SSTL-2 CLASS I" -to mem_addr[0] 
set_instance_assignment -name IO_STANDARD "SSTL-2 CLASS I" -to mem_addr[1] 
set_instance_assignment -name IO_STANDARD "SSTL-2 CLASS I" -to mem_addr[2] 
set_instance_assignment -name IO_STANDARD "SSTL-2 CLASS I" -to mem_addr[3] 
set_instance_assignment -name IO_STANDARD "SSTL-2 CLASS I" -to mem_addr[4] 
set_instance_assignment -name IO_STANDARD "SSTL-2 CLASS I" -to mem_addr[5] 
set_instance_assignment -name IO_STANDARD "SSTL-2 CLASS I" -to mem_addr[6] 
set_instance_assignment -name IO_STANDARD "SSTL-2 CLASS I" -to mem_addr[7] 
set_instance_assignment -name IO_STANDARD "SSTL-2 CLASS I" -to mem_addr[8] 
set_instance_assignment -name IO_STANDARD "SSTL-2 CLASS I" -to mem_addr[9] 
set_instance_assignment -name IO_STANDARD "SSTL-2 CLASS I" -to mem_addr[10] 
set_instance_assignment -name IO_STANDARD "SSTL-2 CLASS I" -to mem_addr[11] 
set_instance_assignment -name IO_STANDARD "SSTL-2 CLASS I" -to mem_addr[12] 
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to mem_ba[0] 
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to mem_ba[1] 
set_instance_assignment -name IO_STANDARD "SSTL-2 CLASS I" -to mem_ba[0] 
set_instance_assignment -name IO_STANDARD "SSTL-2 CLASS I" -to mem_ba[1] 
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to mem_ras_n 
set_instance_assignment -name IO_STANDARD "SSTL-2 CLASS I" -to mem_ras_n 
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to mem_cas_n 
set_instance_assignment -name IO_STANDARD "SSTL-2 CLASS I" -to mem_cas_n 
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to mem_we_n 
set_instance_assignment -name IO_STANDARD "SSTL-2 CLASS I" -to mem_we_n 
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to mem_dq[0] 
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to mem_dq[1] 
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to mem_dq[2] 
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to mem_dq[3] 
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to mem_dq[4] 
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to mem_dq[5] 
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to mem_dq[6] 
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to mem_dq[7] 
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to mem_dq[8] 
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to mem_dq[9] 
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to mem_dq[10] 
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to mem_dq[11] 
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to mem_dq[12] 
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to mem_dq[13] 
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to mem_dq[14] 
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to mem_dq[15] 
set_instance_assignment -name OUTPUT_ENABLE_GROUP 1244174944 -to mem_dq[0] 
set_instance_assignment -name OUTPUT_ENABLE_GROUP 1244174944 -to mem_dq[1] 
set_instance_assignment -name OUTPUT_ENABLE_GROUP 1244174944 -to mem_dq[2] 
set_instance_assignment -name OUTPUT_ENABLE_GROUP 1244174944 -to mem_dq[3] 
set_instance_assignment -name OUTPUT_ENABLE_GROUP 1244174944 -to mem_dq[4] 
set_instance_assignment -name OUTPUT_ENABLE_GROUP 1244174944 -to mem_dq[5] 
set_instance_assignment -name OUTPUT_ENABLE_GROUP 1244174944 -to mem_dq[6] 
set_instance_assignment -name OUTPUT_ENABLE_GROUP 1244174944 -to mem_dq[7] 
set_instance_assignment -name OUTPUT_ENABLE_GROUP 1244174944 -to mem_dq[8] 
set_instance_assignment -name OUTPUT_ENABLE_GROUP 1244174944 -to mem_dq[9] 
set_instance_assignment -name OUTPUT_ENABLE_GROUP 1244174944 -to mem_dq[10] 
set_instance_assignment -name OUTPUT_ENABLE_GROUP 1244174944 -to mem_dq[11] 
set_instance_assignment -name OUTPUT_ENABLE_GROUP 1244174944 -to mem_dq[12] 
set_instance_assignment -name OUTPUT_ENABLE_GROUP 1244174944 -to mem_dq[13] 
set_instance_assignment -name OUTPUT_ENABLE_GROUP 1244174944 -to mem_dq[14] 
set_instance_assignment -name OUTPUT_ENABLE_GROUP 1244174944 -to mem_dq[15] 
set_instance_assignment -name IO_STANDARD "SSTL-2 CLASS I" -to mem_dq[0] 
set_instance_assignment -name IO_STANDARD "SSTL-2 CLASS I" -to mem_dq[1] 
set_instance_assignment -name IO_STANDARD "SSTL-2 CLASS I" -to mem_dq[2] 
set_instance_assignment -name IO_STANDARD "SSTL-2 CLASS I" -to mem_dq[3] 
set_instance_assignment -name IO_STANDARD "SSTL-2 CLASS I" -to mem_dq[4] 
set_instance_assignment -name IO_STANDARD "SSTL-2 CLASS I" -to mem_dq[5] 
set_instance_assignment -name IO_STANDARD "SSTL-2 CLASS I" -to mem_dq[6] 
set_instance_assignment -name IO_STANDARD "SSTL-2 CLASS I" -to mem_dq[7] 
set_instance_assignment -name IO_STANDARD "SSTL-2 CLASS I" -to mem_dq[8] 
set_instance_assignment -name IO_STANDARD "SSTL-2 CLASS I" -to mem_dq[9] 
set_instance_assignment -name IO_STANDARD "SSTL-2 CLASS I" -to mem_dq[10] 
set_instance_assignment -name IO_STANDARD "SSTL-2 CLASS I" -to mem_dq[11] 
set_instance_assignment -name IO_STANDARD "SSTL-2 CLASS I" -to mem_dq[12] 
set_instance_assignment -name IO_STANDARD "SSTL-2 CLASS I" -to mem_dq[13] 
set_instance_assignment -name IO_STANDARD "SSTL-2 CLASS I" -to mem_dq[14] 
set_instance_assignment -name IO_STANDARD "SSTL-2 CLASS I" -to mem_dq[15] 
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to mem_dqs[0] 
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to mem_dqs[1] 
set_instance_assignment -name OUTPUT_ENABLE_GROUP 1244174944 -to mem_dqs[0] 
set_instance_assignment -name OUTPUT_ENABLE_GROUP 1244174944 -to mem_dqs[1] 
set_instance_assignment -name IO_STANDARD "SSTL-2 CLASS I" -to mem_dqs[0] 
set_instance_assignment -name IO_STANDARD "SSTL-2 CLASS I" -to mem_dqs[1] 
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to mem_dm[0] 
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to mem_dm[1] 
set_instance_assignment -name OUTPUT_ENABLE_GROUP 1244174944 -to mem_dm[0] 
set_instance_assignment -name OUTPUT_ENABLE_GROUP 1244174944 -to mem_dm[1] 
set_instance_assignment -name IO_STANDARD "SSTL-2 CLASS I" -to mem_dm[0] 
set_instance_assignment -name IO_STANDARD "SSTL-2 CLASS I" -to mem_dm[1]