# TCL File Generated by Component Editor 11.0sp1
# Tue Sep 10 15:37:28 BST 2013
# DO NOT MODIFY


# +-----------------------------------
# | 
# | my_pwm "Generic pwm with 16 bit duty cycle" v2.0
# | NGunton 2013.09.10.15:37:28
# | registers with 16 bit duty cycle and 32 bit clock divide
# | 
# | /home/ngunton/Altera_Systems_Labs/EDM_Enhanced/pwm_simple/nios/my_pwm_1/my_pwm.vhd
# | 
# |    ./my_pwm.vhd syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 11.0
# | 
package require -exact sopc 11.0
# | 
# +-----------------------------------

# +-----------------------------------
# | module my_pwm
# | 
set_module_property DESCRIPTION "registers with 16 bit duty cycle and 32 bit clock divide"
set_module_property NAME my_pwm
set_module_property VERSION 2.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "Peripherals/Microcontroller Peripherals"
set_module_property AUTHOR NGunton
set_module_property DISPLAY_NAME "Generic pwm with 16 bit duty cycle"
set_module_property TOP_LEVEL_HDL_FILE my_pwm.vhd
set_module_property TOP_LEVEL_HDL_MODULE my_pwm
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL TRUE
set_module_property STATIC_TOP_LEVEL_MODULE_NAME my_pwm
set_module_property FIX_110_VIP_PATH false
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file my_pwm.vhd {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock
# | 
add_interface clock clock end
set_interface_property clock clockRate 0

set_interface_property clock ENABLED true

add_interface_port clock clk clk Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point pwm_16
# | 
add_interface pwm_16 avalon end
set_interface_property pwm_16 addressAlignment DYNAMIC
set_interface_property pwm_16 addressUnits WORDS
set_interface_property pwm_16 associatedClock clock
set_interface_property pwm_16 burstOnBurstBoundariesOnly false
set_interface_property pwm_16 explicitAddressSpan 0
set_interface_property pwm_16 holdTime 0
set_interface_property pwm_16 isMemoryDevice false
set_interface_property pwm_16 isNonVolatileStorage false
set_interface_property pwm_16 linewrapBursts false
set_interface_property pwm_16 maximumPendingReadTransactions 0
set_interface_property pwm_16 printableDevice false
set_interface_property pwm_16 readLatency 0
set_interface_property pwm_16 readWaitTime 1
set_interface_property pwm_16 setupTime 0
set_interface_property pwm_16 timingUnits Cycles
set_interface_property pwm_16 writeWaitTime 0

set_interface_property pwm_16 ENABLED true

add_interface_port pwm_16 data_in writedata Input 32
add_interface_port pwm_16 address address Input 2
add_interface_port pwm_16 wr_n write_n Input 1
add_interface_port pwm_16 cs_n chipselect_n Input 1
add_interface_port pwm_16 data_out readdata Output 32
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point reset
# | 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT

set_interface_property reset ENABLED true

add_interface_port reset resetn reset_n Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point pwm_out
# | 
add_interface pwm_out conduit end

set_interface_property pwm_out ENABLED true

add_interface_port pwm_out pwm_out export Output 1
# | 
# +-----------------------------------
